- 👋 Hi, I’m @OdinaxonAbdurashidova
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
- 
# Connects to the remote repository 
git remote -v
 # Verifies the new remote URL 
<!---
OdinaxonAbdurashidova/OdinaxonAbdurashidova is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
